version: "3.8"
services:
  db:
    image: postgres
    container_name: integrationTestCompose
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
