name: CI/CD Pipleline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy .env.example to env
        run: cp .env.example .env
      - name: Grant execution permission to the script
        run: chmod +x ./scripts/run-integration.sh
      - name: Run integration script
        run: npm run test:integration
